version: '3'

services:
  maru_lake:
    container_name: maru_lake
    image: maru_lake:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NODE: production
    restart: always
    ports:
      - 9022:3000
